name: "Install toolchains"
description: "Install toolchains"
runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.74
        override: true
        target: wasm32-unknown-unknown
        components: rustfmt
    - run: cargo install wasm-tools blake2_bin
      shell: bash

