[package]
name = "qjs"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[profile.release]
debug-assertions = false
overflow-checks = false

[dependencies]
ink = { version = "4", default-features = false, features = ["no-allocator"]}
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
dlmalloc = { version = "0.2.4", default-features = false, features = ["global"] }
qjs-sys = { path = "qjs-sys" }
pink-extension = { version = "0.4", default-features = false }
bootcode = { path = "bootcode" }

[lib]
name = "qjs"
path = "lib.rs"
crate-type = [
	"cdylib",
	"rlib",
]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "serde/std",
    "serde_json/std",
    "pink-extension/std",
]
ink-as-dependency = []
