[package]
name = "qjs"
version = "1.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[profile.release]
debug-assertions = false
overflow-checks = false

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
qjs-sys = { path = "qjs-sys" }
bootcode = { path = "bootcode" }
sidevm = "0.1.10"
log = "0.4"
tokio = { version = "1", features = ["sync", "macros"] }
anyhow = "1.0"

[lib]
name = "qjs"
crate-type = ["cdylib"]

[features]
