name: Build contracts
description: Build contracts
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install_toolchain
    - name: Install deps
      run: sudo bash scripts/install-requirements.sh
      shell: bash
    - name: Install cargo-contract
      run: cargo install cargo-contract --version=^2 --locked
      shell: bash
    - name: Install rust components
      run: rustup component add rust-src && rustup target add wasm32-wasi
      shell: bash
    - name: Build contracts
      run: cargo contract build --release
      shell: bash
