name: Build and release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/build-contracts

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          body: Nightly build
          files: |
            ./target/ink/qjs.contract
            ./target/ink/qjs.wasm
            ./target/ink/qjs.json
