name: Build and release

on:
  workflow_dispatch:
  push:
    tags:
      - "pink-quickjs-v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/install_toolchain
      - name: Install deps
        run: sudo bash scripts/install-requirements.sh
        shell: bash
      - name: Install rust components
        run: rustup component add rust-src
        shell: bash
      - name: Install cargo-contract
        run: cargo install cargo-contract --version=^4.0.0-alpha --locked
        shell: bash
      - name: Build pink-quickjs
        run: make opt -C pink-quickjs
        shell: bash
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: true
          files: |
            pink-quickjs/target/ink/*.contract
            pink-quickjs/target/ink/*.json
            pink-quickjs/target/ink/*.wasm
