name: Build and release

on:
  workflow_dispatch:
  push:
    tags:
      - "sidevm-quickjs-v*.*.*"
      - "sidevm-quickjs-v*.*.*-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/install_toolchain
      - name: Install Binaryen
        run: |
          wget https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz
          tar -xzvf binaryen-version_116-x86_64-linux.tar.gz -C $RUNNER_TEMP/
          echo "$RUNNER_TEMP/binaryen-version_116/bin" >> $GITHUB_PATH
      - name: Install deps
        run: sudo bash scripts/install-requirements.sh
        shell: bash
      - name: Install rust components
        run: rustup component add rust-src && rustup target add wasm32-wasi
        shell: bash
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli --git https://github.com/kvinwang/wasm-bindgen --branch workaround
        shell: bash
      - name: Build sidevm-quickjs
        run: make opt -C sidevm-quickjs
        shell: bash
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: true
          files: |
            sidevm-quickjs/*.wasm
            sidevm-quickjs/phatjs-x86_64-unknown-linux-musl
            sidevm-quickjs/hash.txt
            sidevm-quickjs/phatjs-web.tar.gz
            sidevm-quickjs/phatjs-nodejs.tar.gz
